export const logosList = [
	{ text: "Kira", value: "kira-128.png" },
	{ text: "Anox", value: "anox-128.png" },
	{ text: "Games Academy", value: "games-academy-128.png" },
	{ text: "Nochance", value: "nochance-128.png" },
	{ text: "Granted", value: "granted-128.png" },
	{ text: "No Sir!", value: "no-sir!-128.png" },
	{ text: "Team Mces", value: "team-mces-128.png" },
	{ text: "Tnc Predator", value: "tnc-predator-128.png" },
	{ text: "Supermassive Esports", value: "supermassive-esports-128.png" },
	{ text: "Pact", value: "pact-128.png" },
	{ text: "North", value: "north-128.png" },
	{ text: "Seven Wars E Sports", value: "seven-wars-e-sports-128.png" },
	{ text: "Galakticos", value: "galakticos-128.png" },
	{ text: "Vae Victis", value: "vae-victis-128.png" },
	{ text: "Gameagents", value: "gameagents-128.png" },
	{ text: "Burden United", value: "burden-united-128.png" },
	{ text: "Rex Regum Qeon", value: "rex-regum-qeon-128.png" },
	{ text: "Academy Of Esports", value: "academy-of-esports-128.png" },
	{ text: "Vexed Gaming", value: "vexed-gaming-128.png" },
	{ text: "Animal Squad", value: "animal-squad-128.png" },
	{ text: "Team Lioncast", value: "team-lioncast-128.png" },
	{ text: "Skitlite", value: "skitlite-128.png" },
	{ text: "Team Plan B", value: "team-plan-b-128.png" },
	{ text: "Asus Rog Elite", value: "asus-rog-elite-128.png" },
	{ text: "Forward Gaming", value: "forward-gaming-128.png" },
	{ text: "Flaming Cyborg", value: "flaming-cyborg-128.png" },
	{ text: "Uniquestars", value: "uniquestars-128.png" },
	{ text: "Athletico Esports", value: "athletico-esports-128.png" },
	{ text: "Helsinki Reds", value: "helsinki-reds-128.png" },
	{ text: "Windigo.vbet Academy", value: "windigo.vbet-academy-128.png" },
	{ text: "Keen Gaming.luminous", value: "keen-gaming.luminous-128.png" },
	{ text: "Athletico", value: "athletico-128.png" },
	{ text: "V3 Esports", value: "v3-esports-128.png" },
	{ text: "Kon Sweden", value: "kon-sweden-128.png" },
	{ text: "Kuala Lumpur Hunters", value: "kuala-lumpur-hunters-128.png" },
	{ text: "Rogue Warriors", value: "rogue-warriors-128.png" },
	{ text: "Havu Gaming", value: "havu-gaming-128.png" },
	{ text: "87", value: "87-128.png" },
	{ text: "Se7en Esports", value: "se7en-esports-128.png" },
	{ text: "Pixel Esports Club", value: "pixel-esports-club-128.png" },
	{ text: "Neverplay", value: "neverplay-128.png" },
	{ text: "Asterisk", value: "asterisk-128.png" },
	{ text: "Jiezou", value: "jiezou-128.png" },
	{ text: "Team Forge", value: "team-forge-128.png" },
	{ text: "Chiefs Esports", value: "chiefs-esports-128.png" },
	{ text: "Epiphany Bolt", value: "epiphany-bolt-128.png" },
	{ text: "Penta Sports", value: "penta-sports-128.png" },
	{ text: "Wheel Whreck", value: "wheel-whreck-128.png" },
	{ text: "The Pango", value: "the-pango-128.png" },
	{ text: "Mvp Karnal", value: "mvp-karnal-128.png" },
	{ text: "Bang", value: "bang-128.png" },
	{ text: "Alsen Team", value: "alsen-team-128.png" },
	{ text: "Mammoth Esports", value: "mammoth-esports-128.png" },
	{ text: "Igame.com", value: "igame.com-128.png" },
	{ text: "Team Xenex", value: "team-xenex-128.png" },
	{ text: "Team Agg", value: "team-agg-128.png" },
	{ text: "Quantic Gaming", value: "quantic-gaming-128.png" },
	{ text: "Immortoru", value: "immortoru-128.png" },
	{ text: "Machi 17", value: "machi-17-128.png" },
	{ text: "Top Esports Challenger", value: "top-esports-challenger-128.png" },
	{ text: "Tornado Rox", value: "tornado-rox-128.png" },
	{ text: "Sengoku Gaming", value: "sengoku-gaming-128.png" },
	{ text: "No Bounty Hunter", value: "no-bounty-hunter-128.png" },
	{ text: "G2 Heretics", value: "g2-heretics-128.png" },
	{ text: "Team Nxl", value: "team-nxl-128.png" },
	{ text: "Team Empire Hope", value: "team-empire-hope-128.png" },
	{ text: "Piratesports", value: "piratesports-128.png" },
	{ text: "Nopangolier", value: "nopangolier-128.png" },
	{ text: "Nl", value: "nl-128.png" },
	{ text: "Sandbox Gaming", value: "sandbox-gaming-128.png" },
	{ text: "Shadowcream", value: "shadowcream-128.png" },
	{ text: "Tcm Gaming", value: "tcm-gaming-128.png" },
	{ text: "Sinodragon Gaming", value: "sinodragon-gaming-128.png" },
	{ text: "Curse Gaming", value: "curse-gaming-128.png" },
	{ text: "Fireloli", value: "fireloli-128.png" },
	{ text: "Control Esports", value: "control-esports-128.png" },
	{ text: "Amazing Gaming", value: "amazing-gaming-128.png" },
	{ text: "Mousesports", value: "mousesports-128.png" },
	{ text: "Team Unique", value: "team-unique-128.png" },
	{ text: "Bulldozer Esports", value: "bulldozer-esports-128.png" },
	{ text: "Wizards E Sports Club", value: "wizards-e-sports-club-128.png" },
	{ text: "The Mongolz", value: "the-mongolz-128.png" },
	{ text: "Lgb Esports", value: "lgb-esports-128.png" },
	{ text: "Cnb E Sports Club", value: "cnb-e-sports-club-128.png" },
	{ text: "Blight Gaming", value: "blight-gaming-128.png" },
	{ text: "Pichau", value: "pichau-128.png" },
	{ text: "Silver Crows", value: "silver-crows-128.png" },
	{ text: "Team Just", value: "team-just-128.png" },
	{ text: "Beyond Esports", value: "beyond-esports-128.png" },
	{ text: "Myxmg", value: "myxmg-128.png" },
	{ text: "Backpacks Gaming", value: "backpacks-gaming-128.png" },
	{ text: "Windigo", value: "windigo-128.png" },
	{ text: "1907 Fenerbahce", value: "1907-fenerbahce-128.png" },
	{ text: "Ig.vitality", value: "ig.vitality-128.png" },
	{ text: "Apk Prince", value: "apk-prince-128.png" },
	{ text: "Detonation Gaming", value: "detonation-gaming-128.png" },
	{ text: "Fraternitas", value: "fraternitas-128.png" },
	{ text: "H2k Gaming", value: "h2k-gaming-128.png" },
	{ text: "Nao Tem Como", value: "nao-tem-como-128.png" },
	{ text: "Menace Gg", value: "menace-gg-128.png" },
	{ text: "Nerdrage", value: "nerdrage-128.png" },
	{ text: "Caladrius", value: "caladrius-128.png" },
	{ text: "Fnatic", value: "fnatic-128.png" },
	{ text: "Vici Gaming Potential", value: "vici-gaming-potential-128.png" },
	{ text: "Natus Vincere", value: "natus-vincere-128.png" },
	{ text: "Sprout", value: "sprout-128.png" },
	{ text: "Bravado Gaming", value: "bravado-gaming-128.png" },
	{ text: "Suning Gaming", value: "suning-gaming-128.png" },
	{ text: "Imperial", value: "imperial-128.png" },
	{ text: "Doublelift", value: "doublelift-128.png" },
	{ text: "I May", value: "i-may-128.png" },
	{ text: "Winners", value: "winners-128.png" },
	{ text: "Origen Bcn", value: "origen-bcn-128.png" },
	{ text: "Icon", value: "icon-128.png" },
	{ text: "Ehome", value: "ehome-128.png" },
	{ text: "Ffqtv Gaming", value: "ffqtv-gaming-128.png" },
	{ text: "Newbee", value: "newbee-128.png" },
	{ text: "Team Innova", value: "team-innova-128.png" },
	{ text: "Redline Esports", value: "redline-esports-128.png" },
	{ text: "Kpi Gaming", value: "kpi-gaming-128.png" },
	{ text: "Furious Gaming", value: "furious-gaming-128.png" },
	{ text: "Paranoia Esports", value: "paranoia-esports-128.png" },
	{ text: "Optic Gaming", value: "optic-gaming-128.png" },
	{ text: "Dts Gaming", value: "dts-gaming-128.png" },
	{ text: "Csgo2x.com", value: "csgo2x.com-128.png" },
	{ text: "Game Pub", value: "game-pub-128.png" },
	{ text: "J.storm", value: "j.storm-128.png" },
	{ text: "North Academy", value: "north-academy-128.png" },
	{ text: "Vgflashgaming", value: "vgflashgaming-128.png" },
	{ text: "Nexus Gamers Pub", value: "nexus-gamers-pub-128.png" },
	{ text: "Lng Gaming", value: "lng-gaming-128.png" },
	{ text: "Vitality", value: "vitality-128.png" },
	{ text: "Kerchnet", value: "kerchnet-128.png" },
	{ text: "Gorillaz Pride", value: "gorillaz-pride-128.png" },
	{ text: "Winstrike", value: "winstrike-128.png" },
	{ text: "Dan Gaming", value: "dan-gaming-128.png" },
	{ text: "Bigtime Regal", value: "bigtime-regal-128.png" },
	{ text: "Mvp Space", value: "mvp-space-128.png" },
	{ text: "Kongdoo Monster", value: "kongdoo-monster-128.png" },
	{ text: "Team Yp", value: "team-yp-128.png" },
	{ text: "Team Aaa", value: "team-aaa-128.png" },
	{ text: "Phong Vu Buffalo", value: "phong-vu-buffalo-128.png" },
	{ text: "Expert Gaming", value: "expert-gaming-128.png" },
	{ text: "Wysix", value: "wysix-128.png" },
	{ text: "Team Imperio Multimedia", value: "team-imperio-multimedia-128.png" },
	{ text: "Iceberg Esports", value: "iceberg-esports-128.png" },
	{ text: "Team Amplfy", value: "team-amplfy-128.png" },
	{ text: "Millenium", value: "millenium-128.png" },
	{ text: "Gf Gaming", value: "gf-gaming-128.png" },
	{ text: "Scorpiogame", value: "scorpiogame-128.png" },
	{ text: "Overgaming", value: "overgaming-128.png" },
	{ text: "2990 Esports", value: "2990-esports-128.png" },
	{ text: "Team Queso", value: "team-queso-128.png" },
	{ text: "Mortality Esports", value: "mortality-esports-128.png" },
	{ text: "Efrog", value: "efrog-128.png" },
	{ text: "London Esports", value: "london-esports-128.png" },
	{ text: "Clutch Solutions", value: "clutch-solutions-128.png" },
	{ text: "Mlxg", value: "mlxg-128.png" },
	{ text: "Intact", value: "intact-128.png" },
	{ text: "Cloud9", value: "cloud9-128.png" },
	{ text: "Avant Garde", value: "avant-garde-128.png" },
	{ text: "Virtue Gaming", value: "virtue-gaming-128.png" },
	{ text: "Nemiga Gaming", value: "nemiga-gaming-128.png" },
	{ text: "Detona Gaming", value: "detona-gaming-128.png" },
	{ text: "K1ck Esports.es", value: "k1ck-esports.es-128.png" },
	{ text: "Alpha Esports", value: "alpha-esports-128.png" },
	{ text: "Gdansk Lions", value: "gdansk-lions-128.png" },
	{ text: "Red Instinct", value: "red-instinct-128.png" },
	{ text: "Endpoint", value: "endpoint-128.png" },
	{ text: "4kings", value: "4kings-128.png" },
	{ text: "Ever8 Winners", value: "ever8-winners-128.png" },
	{ text: "Furia Gaming", value: "furia-gaming-128.png" },
	{ text: "Ascension Gaming", value: "ascension-gaming-128.png" },
	{ text: "Unchained Esports", value: "unchained-esports-128.png" },
	{ text: "Team Aurora", value: "team-aurora-128.png" },
	{ text: "Off Balance Gaming", value: "off-balance-gaming-128.png" },
	{ text: "Atlantis Esports", value: "atlantis-esports-128.png" },
	{ text: "Gus Gaming", value: "gus-gaming-128.png" },
	{ text: "Enzo", value: "enzo-128.png" },
	{ text: "Zaga Talent Gaming", value: "zaga-talent-gaming-128.png" },
	{ text: "Starluck", value: "starluck-128.png" },
	{ text: "Baskonia Esports", value: "baskonia-esports-128.png" },
	{ text: "Invictus Gaming Youth", value: "invictus-gaming-youth-128.png" },
	{ text: "The Foundation", value: "the-foundation-128.png" },
	{ text: "Movistar Riders", value: "movistar-riders-128.png" },
	{ text: "Clutch", value: "clutch-128.png" },
	{ text: "Pro100", value: "pro100-128.png" },
	{ text: "Team Ldlc.com", value: "team-ldlc.com-128.png" },
	{ text: "Team1", value: "team1-128.png" },
	{ text: "Flyquest Esports", value: "flyquest-esports-128.png" },
	{ text: "T Show", value: "t-show-128.png" },
	{ text: "Majestic Lions", value: "majestic-lions-128.png" },
	{ text: "Mysterious Monkeys", value: "mysterious-monkeys-128.png" },
	{ text: "Mineski.ggnetwork", value: "mineski.ggnetwork-128.png" },
	{ text: "Qiao Gu Reapers", value: "qiao-gu-reapers-128.png" },
	{ text: "Vikings Gaming", value: "vikings-gaming-128.png" },
	{ text: "Universal Soldiers", value: "universal-soldiers-128.png" },
	{ text: "Dreamworks", value: "dreamworks-128.png" },
	{ text: "Lyon Gaming", value: "lyon-gaming-128.png" },
	{ text: "Diamondprox", value: "diamondprox-128.png" },
	{ text: "Odium", value: "odium-128.png" },
	{ text: "Burning Core", value: "burning-core-128.png" },
	{ text: "Trypants", value: "trypants-128.png" },
	{ text: "Kaos Latin Gamers", value: "kaos-latin-gamers-128.png" },
	{ text: "Fierce Esports", value: "fierce-esports-128.png" },
	{ text: "Lazarus Esports", value: "lazarus-esports-128.png" },
	{ text: "Resolute", value: "resolute-128.png" },
	{ text: "Elevate", value: "elevate-128.png" },
	{ text: "Mad Lions E.c.", value: "mad-lions-e.c.-128.png" },
	{ text: "Gamers2", value: "gamers2-128.png" },
	{ text: "Buykey Esports", value: "buykey-esports-128.png" },
	{ text: "Westdoor", value: "westdoor-128.png" },
	{ text: "Omg", value: "omg-128.png" },
	{ text: "Caz Esports", value: "caz-esports-128.png" },
	{ text: "Team Liquid Academy", value: "team-liquid-academy-128.png" },
	{ text: "Detonation Focusme", value: "detonation-focusme-128.png" },
	{ text: "Headshotbg", value: "headshotbg-128.png" },
	{ text: "Natus Vincere Cis", value: "natus-vincere-cis-128.png" },
	{ text: "Kaipi", value: "kaipi-128.png" },
	{ text: "Bigetron E Sports", value: "bigetron-e-sports-128.png" },
	{ text: "The Gatekeepers", value: "the-gatekeepers-128.png" },
	{ text: "Brtt", value: "brtt-128.png" },
	{ text: "Pain Gaming", value: "pain-gaming-128.png" },
	{ text: "Against All Authority", value: "against-all-authority-128.png" },
	{ text: "Avalon Club", value: "avalon-club-128.png" },
	{ text: "Team Atlantis", value: "team-atlantis-128.png" },
	{ text: "Imperial Dragons", value: "imperial-dragons-128.png" },
	{ text: "Red Reserve", value: "red-reserve-128.png" },
	{ text: "Dragon Army", value: "dragon-army-128.png" },
	{ text: "Team We Academy", value: "team-we-academy-128.png" },
	{ text: "Afreeca Freecs", value: "afreeca-freecs-128.png" },
	{ text: "Machi E Sports", value: "machi-e-sports-128.png" },
	{ text: "Qtv Gaming", value: "qtv-gaming-128.png" },
	{ text: "Copenhagen Wolves", value: "copenhagen-wolves-128.png" },
	{ text: "Team Ancient", value: "team-ancient-128.png" },
	{ text: "Lgd Forever Young", value: "lgd-forever-young-128.png" },
	{ text: "Exploits Esports", value: "exploits-esports-128.png" },
	{ text: "Ftd Club A", value: "ftd-club-a-128.png" },
	{ text: "Triple", value: "triple-128.png" },
	{ text: "Imaqtpie", value: "imaqtpie-128.png" },
	{ text: "Space Soldiers", value: "space-soldiers-128.png" },
	{ text: "Luminosity Gaming", value: "luminosity-gaming-128.png" },
	{ text: "Es Sharks", value: "es-sharks-128.png" },
	{ text: "Ksv Esports", value: "ksv-esports-128.png" },
	{ text: "Prodota Gaming", value: "prodota-gaming-128.png" },
	{ text: "Royal Youth", value: "royal-youth-128.png" },
	{ text: "Defusekids", value: "defusekids-128.png" },
	{ text: "Rogue Warriors Shark", value: "rogue-warriors-shark-128.png" },
	{ text: "Vindicta", value: "vindicta-128.png" },
	{ text: "Eyesports", value: "eyesports-128.png" },
	{ text: "Ambush E Sport", value: "ambush-e-sport-128.png" },
	{ text: "Sk Telecom T1", value: "sk-telecom-t1-128.png" },
	{ text: "Flash Gaming", value: "flash-gaming-128.png" },
	{ text: "Broxah", value: "broxah-128.png" },
	{ text: "Team Catch Gamer", value: "team-catch-gamer-128.png" },
	{ text: "Fc Schalke 04 Esports", value: "fc-schalke-04-esports-128.png" },
	{ text: "Vexed.ebuyer", value: "vexed.ebuyer-128.png" },
	{ text: "Golden Guardians Academy", value: "golden-guardians-academy-128.png" },
	{ text: "M0nster.kr", value: "m0nster.kr-128.png" },
	{ text: "Echo Fox", value: "echo-fox-128.png" },
	{ text: "Capri", value: "capri-128.png" },
	{ text: "Chaos Esports Club", value: "chaos-esports-club-128.png" },
	{ text: "Arena Bulls", value: "arena-bulls-128.png" },
	{ text: "Dominus Esports", value: "dominus-esports-128.png" },
	{ text: "Mvp Hot6ix", value: "mvp-hot6ix-128.png" },
	{ text: "Reason Gaming.uk", value: "reason-gaming.uk-128.png" },
	{ text: "Fireball", value: "fireball-128.png" },
	{ text: "E Frag", value: "e-frag-128.png" },
	{ text: "Rush3d", value: "rush3d-128.png" },
	{ text: "Vination Esports E.v.", value: "vination-esports-e.v.-128.png" },
	{ text: "Epikk Esports", value: "epikk-esports-128.png" },
	{ text: "Revival Gaming", value: "revival-gaming-128.png" },
	{ text: "Expert Esport", value: "expert-esport-128.png" },
	{ text: "Navi", value: "navi-128.png" },
	{ text: "Team Secret", value: "team-secret-128.png" },
	{ text: "Nightblue3", value: "nightblue3-128.png" },
	{ text: "Luciddream.138", value: "luciddream.138-128.png" },
	{ text: "Tainted Minds", value: "tainted-minds-128.png" },
	{ text: "Team Vsg", value: "team-vsg-128.png" },
	{ text: "Unsold Stuff Gaming", value: "unsold-stuff-gaming-128.png" },
	{ text: "Fate", value: "fate-128.png" },
	{ text: "Last Kings", value: "last-kings-128.png" },
	{ text: "M19", value: "m19-128.png" },
	{ text: "Lemondogs", value: "lemondogs-128.png" },
	{ text: "Ceros", value: "ceros-128.png" },
	{ text: "Lowkey Esports.vietnam", value: "lowkey-esports.vietnam-128.png" },
	{ text: "Imaginary Gaming", value: "imaginary-gaming-128.png" },
	{ text: "Rockky", value: "rockky-128.png" },
	{ text: "Santos E Sports", value: "santos-e-sports-128.png" },
	{ text: "Cube Adonis", value: "cube-adonis-128.png" },
	{ text: "Soar Gaming", value: "soar-gaming-128.png" },
	{ text: "Born Of Fire", value: "born-of-fire-128.png" },
	{ text: "Team Exile", value: "team-exile-128.png" },
	{ text: "Torpedo", value: "torpedo-128.png" },
	{ text: "Choke Gaming", value: "choke-gaming-128.png" },
	{ text: "Licorice", value: "licorice-128.png" },
	{ text: "Team Envy", value: "team-envy-128.png" },
	{ text: "Thunder Awaken", value: "thunder-awaken-128.png" },
	{ text: "Lowlandlions", value: "lowlandlions-128.png" },
	{ text: "Warriorsgaming.unity", value: "warriorsgaming.unity-128.png" },
	{ text: "No Problem!", value: "no-problem!-128.png" },
	{ text: "Fgb Gaming", value: "fgb-gaming-128.png" },
	{ text: "Madlikewizards", value: "madlikewizards-128.png" },
	{ text: "Infamous", value: "infamous-128.png" },
	{ text: "Explosive", value: "explosive-128.png" },
	{ text: "Topsports Esports", value: "topsports-esports-128.png" },
	{ text: "Rude", value: "rude-128.png" },
	{ text: "Znation", value: "znation-128.png" },
	{ text: "Rebels", value: "rebels-128.png" },
	{ text: "Besitkas Esports Club", value: "besitkas-esports-club-128.png" },
	{ text: "Rascal Jester", value: "rascal-jester-128.png" },
	{ text: "Rooster", value: "rooster-128.png" },
	{ text: "Team Alientech", value: "team-alientech-128.png" },
	{ text: "Goodgame", value: "goodgame-128.png" },
	{ text: "Ace Gaming", value: "ace-gaming-128.png" },
	{ text: "Gux Friends", value: "gux-friends-128.png" },
	{ text: "Copenhagen Flames", value: "copenhagen-flames-128.png" },
	{ text: "Xgame.kz", value: "xgame.kz-128.png" },
	{ text: "D13", value: "d13-128.png" },
	{ text: "Dumbledoge", value: "dumbledoge-128.png" },
	{ text: "Dat Team", value: "dat-team-128.png" },
	{ text: "Oh My Dream", value: "oh-my-dream-128.png" },
	{ text: "G2 Esports", value: "g2-esports-128.png" },
	{ text: "Keyd Stars", value: "keyd-stars-128.png" },
	{ text: "Flamengo Esports", value: "flamengo-esports-128.png" },
	{ text: "Lets Do It", value: "lets-do-it-128.png" },
	{ text: "Hyperx Fr34kshow", value: "hyperx-fr34kshow-128.png" },
	{ text: "Kabum! E Sports", value: "kabum!-e-sports-128.png" },
	{ text: "Manatee Esports", value: "manatee-esports-128.png" },
	{ text: "Ence Esports", value: "ence-esports-128.png" },
	{ text: "Pentagram", value: "pentagram-128.png" },
	{ text: "Tricked Esport", value: "tricked-esport-128.png" },
	{ text: "Detonator", value: "detonator-128.png" },
	{ text: "Depre", value: "depre-128.png" },
	{ text: "Planet Odd", value: "planet-odd-128.png" },
	{ text: "Noa", value: "noa-128.png" },
	{ text: "Vireo.pro", value: "vireo.pro-128.png" },
	{ text: "Hs.gg", value: "hs.gg-128.png" },
	{ text: "Dashing Buffalo", value: "dashing-buffalo-128.png" },
	{ text: "Risky Gaming", value: "risky-gaming-128.png" },
	{ text: "Energy Esports", value: "energy-esports-128.png" },
	{ text: "Flashinthenight", value: "flashinthenight-128.png" },
	{ text: "Ehome.immortal", value: "ehome.immortal-128.png" },
	{ text: "All Knights", value: "all-knights-128.png" },
	{ text: "Pixelfire Gaming", value: "pixelfire-gaming-128.png" },
	{ text: "Monumentalis", value: "monumentalis-128.png" },
	{ text: "Elite Wolves", value: "elite-wolves-128.png" },
	{ text: "Team Roccat", value: "team-roccat-128.png" },
	{ text: "Pnda Gaming", value: "pnda-gaming-128.png" },
	{ text: "Aequus Club", value: "aequus-club-128.png" },
	{ text: "Jin Air Green Wings", value: "jin-air-green-wings-128.png" },
	{ text: "Enemy", value: "enemy-128.png" },
	{ text: "Bulldozer Esport", value: "bulldozer-esport-128.png" },
	{ text: "Bx3 Esports Club", value: "bx3-esports-club-128.png" },
	{ text: "Team Flash", value: "team-flash-128.png" },
	{ text: "Esuba", value: "esuba-128.png" },
	{ text: "Corvidae", value: "corvidae-128.png" },
	{ text: "Team Exile5", value: "team-exile5-128.png" },
	{ text: "Dreameaters", value: "dreameaters-128.png" },
	{ text: "Team Mvp", value: "team-mvp-128.png" },
	{ text: "Thunder Logic", value: "thunder-logic-128.png" },
	{ text: "Joy Dream", value: "joy-dream-128.png" },
	{ text: "2kill Gaming", value: "2kill-gaming-128.png" },
	{ text: "Fnatic Academy", value: "fnatic-academy-128.png" },
	{ text: "Griffin", value: "griffin-128.png" },
	{ text: "Ze Pug Godz", value: "ze-pug-godz-128.png" },
	{ text: "Victory Song Gaming", value: "victory-song-gaming-128.png" },
	{ text: "Brisbane Deceptors", value: "brisbane-deceptors-128.png" },
	{ text: "Top Esports", value: "top-esports-128.png" },
	{ text: "Recca Esports", value: "recca-esports-128.png" },
	{ text: "Quantum Bellator Fire", value: "quantum-bellator-fire-128.png" },
	{ text: "Crew Esports", value: "crew-esports-128.png" },
	{ text: "Izako Boars", value: "izako-boars-128.png" },
	{ text: "Team Server Forge", value: "team-server-forge-128.png" },
	{ text: "Bilibili Gaming", value: "bilibili-gaming-128.png" },
	{ text: "Taichi Gaming", value: "taichi-gaming-128.png" },
	{ text: "Aligon", value: "aligon-128.png" },
	{ text: "Clg Red", value: "clg-red-128.png" },
	{ text: "G4", value: "g4-128.png" },
	{ text: "Csgocasino.net", value: "csgocasino.net-128.png" },
	{ text: "Comanche", value: "comanche-128.png" },
	{ text: "Worst Players", value: "worst-players-128.png" },
	{ text: "Monolith Gaming", value: "monolith-gaming-128.png" },
	{ text: "Intz Genesis", value: "intz-genesis-128.png" },
	{ text: "Team Solomid Academy", value: "team-solomid-academy-128.png" },
	{ text: "Netcodeguides.com", value: "netcodeguides.com-128.png" },
	{ text: "6sense", value: "6sense-128.png" },
	{ text: "Lgd.forever Young", value: "lgd.forever-young-128.png" },
	{ text: "Tectonic", value: "tectonic-128.png" },
	{ text: "100 Thieves Academy", value: "100-thieves-academy-128.png" },
	{ text: "Brave Heart", value: "brave-heart-128.png" },
	{ text: "Clan Mystik", value: "clan-mystik-128.png" },
	{ text: "Giants Gaming", value: "giants-gaming-128.png" },
	{ text: "Misfits Premier", value: "misfits-premier-128.png" },
	{ text: "Sparks Esports", value: "sparks-esports-128.png" },
	{ text: "Mith", value: "mith-128.png" },
	{ text: "Zaga Talent", value: "zaga-talent-128.png" },
	{ text: "Team Blackout", value: "team-blackout-128.png" },
	{ text: "Aristocracy", value: "aristocracy-128.png" },
	{ text: "Kabum Esports", value: "kabum-esports-128.png" },
	{ text: "Lng Academy", value: "lng-academy-128.png" },
	{ text: "Fenix", value: "fenix-128.png" },
	{ text: "Arcade Esports", value: "arcade-esports-128.png" },
	{ text: "Big", value: "big-128.png" },
	{ text: "Lazarus", value: "lazarus-128.png" },
	{ text: "Team Ebettle", value: "team-ebettle-128.png" },
	{ text: "Next Generation", value: "next-generation-128.png" },
	{ text: "Codewise Unicorns", value: "codewise-unicorns-128.png" },
	{ text: "Era", value: "era-128.png" },
	{ text: "Reason Gaming", value: "reason-gaming-128.png" },
	{ text: "Titan", value: "titan-128.png" },
	{ text: "Arkangel", value: "arkangel-128.png" },
	{ text: "496 Gaming", value: "496-gaming-128.png" },
	{ text: "Syf Gaming", value: "syf-gaming-128.png" },
	{ text: "Supernova", value: "supernova-128.png" },
	{ text: "Team Wild", value: "team-wild-128.png" },
	{ text: "Moscow Five", value: "moscow-five-128.png" },
	{ text: "Legatum", value: "legatum-128.png" },
	{ text: "Hong Kong Attitude", value: "hong-kong-attitude-128.png" },
	{ text: "Keyd Stars Female", value: "keyd-stars-female-128.png" },
	{ text: "Team Preparation", value: "team-preparation-128.png" },
	{ text: "Seiya", value: "seiya-128.png" },
	{ text: "Mad Kings", value: "mad-kings-128.png" },
	{ text: "Justice", value: "justice-128.png" },
	{ text: "Infinity Esports Cr", value: "infinity-esports-cr-128.png" },
	{ text: "Csgo.one", value: "csgo.one-128.png" },
	{ text: "Uzi", value: "uzi-128.png" },
	{ text: "Divizon", value: "divizon-128.png" },
	{ text: "Downfall", value: "downfall-128.png" },
	{ text: "Ussr Team", value: "ussr-team-128.png" },
	{ text: "Avant Gaming", value: "avant-gaming-128.png" },
	{ text: "Leisure", value: "leisure-128.png" },
	{ text: "H2k", value: "h2k-128.png" },
	{ text: "Asura", value: "asura-128.png" },
	{ text: "Hundred Thieves", value: "hundred-thieves-128.png" },
	{ text: "Infamous Young", value: "infamous-young-128.png" },
	{ text: "Team Luminary", value: "team-luminary-128.png" },
	{ text: "Misfits", value: "misfits-128.png" },
	{ text: "Mysterious Monkeys E V", value: "mysterious-monkeys-e-v-128.png" },
	{ text: "Kos Latin Gamers", value: "kos-latin-gamers-128.png" },
	{ text: "Onlinebots", value: "onlinebots-128.png" },
	{ text: "Mtw", value: "mtw-128.png" },
	{ text: "United5", value: "united5-128.png" },
	{ text: "Utm Esports", value: "utm-esports-128.png" },
	{ text: "Gambit Gaming", value: "gambit-gaming-128.png" },
	{ text: "Astralis", value: "astralis-128.png" },
	{ text: "Inchk1ng", value: "inchk1ng-128.png" },
	{ text: "Planetkey Dynamics", value: "planetkey-dynamics-128.png" },
	{ text: "Hafnet E Sports", value: "hafnet-e-sports-128.png" },
	{ text: "Rog Esport", value: "rog-esport-128.png" },
	{ text: "Gama Dream", value: "gama-dream-128.png" },
	{ text: "Thunder Predator", value: "thunder-predator-128.png" },
	{ text: "Parallax", value: "parallax-128.png" },
	{ text: "Lg Dire Wolves", value: "lg-dire-wolves-128.png" },
	{ text: "Kingzone Dragonx", value: "kingzone-dragonx-128.png" },
	{ text: "Abyss Esports", value: "abyss-esports-128.png" },
	{ text: "Team Dignitas", value: "team-dignitas-128.png" },
	{ text: "Ensure", value: "ensure-128.png" },
	{ text: "Squared Prospects", value: "squared-prospects-128.png" },
	{ text: "Aura Gaming", value: "aura-gaming-128.png" },
	{ text: "Uppercut Esports", value: "uppercut-esports-128.png" },
	{ text: "Virtual Genesis.anthrax", value: "virtual-genesis.anthrax-128.png" },
	{ text: "Instinct", value: "instinct-128.png" },
	{ text: "W7m Gaming", value: "w7m-gaming-128.png" },
	{ text: "Cr4zy", value: "cr4zy-128.png" },
	{ text: "Fragsters", value: "fragsters-128.png" },
	{ text: "Hwa Gaming", value: "hwa-gaming-128.png" },
	{ text: "Hai", value: "hai-128.png" },
	{ text: "Polar Ace", value: "polar-ace-128.png" },
	{ text: "Entity Gaming", value: "entity-gaming-128.png" },
	{ text: "Vici Gaming", value: "vici-gaming-128.png" },
	{ text: "Etherian", value: "etherian-128.png" },
	{ text: "Gold Coin United", value: "gold-coin-united-128.png" },
	{ text: "Jd Gaming", value: "jd-gaming-128.png" },
	{ text: "Synrgy Gaming", value: "synrgy-gaming-128.png" },
	{ text: "Acion Arena", value: "acion-arena-128.png" },
	{ text: "Rebirth Esports", value: "rebirth-esports-128.png" },
	{ text: "Vgj.storm", value: "vgj.storm-128.png" },
	{ text: "Nordavind", value: "nordavind-128.png" },
	{ text: "Geek Fam", value: "geek-fam-128.png" },
	{ text: "Nasr Esports", value: "nasr-esports-128.png" },
	{ text: "Virtus.pro", value: "virtus.pro-128.png" },
	{ text: "Winning Gaming", value: "winning-gaming-128.png" },
	{ text: "Imay", value: "imay-128.png" },
	{ text: "Maxfloplay", value: "maxfloplay-128.png" },
	{ text: "Yeah", value: "yeah-128.png" },
	{ text: "Brion Blade", value: "brion-blade-128.png" },
	{ text: "Levitate", value: "levitate-128.png" },
	{ text: "Conquest", value: "conquest-128.png" },
	{ text: "Team Descend", value: "team-descend-128.png" },
	{ text: "Team Immunity", value: "team-immunity-128.png" },
	{ text: "For The Win Esports", value: "for-the-win-esports-128.png" },
	{ text: "Arce", value: "arce-128.png" },
	{ text: "G Rex", value: "g-rex-128.png" },
	{ text: "Team One Esports", value: "team-one-esports-128.png" },
	{ text: "Hoorai", value: "hoorai-128.png" },
	{ text: "Enyoy", value: "enyoy-128.png" },
	{ text: "Zeros", value: "zeros-128.png" },
	{ text: "Cpt Jack", value: "cpt-jack-128.png" },
	{ text: "Renegades", value: "renegades-128.png" },
	{ text: "Signature Gaming", value: "signature-gaming-128.png" },
	{ text: "Volgare", value: "volgare-128.png" },
	{ text: "No Quarter Cartel", value: "no-quarter-cartel-128.png" },
	{ text: "Esahara", value: "esahara-128.png" },
	{ text: "Caps", value: "caps-128.png" },
	{ text: "Wayi Spider", value: "wayi-spider-128.png" },
	{ text: "Elements Pro Gaming", value: "elements-pro-gaming-128.png" },
	{ text: "We Are Young", value: "we-are-young-128.png" },
	{ text: "Reubenmaster", value: "reubenmaster-128.png" },
	{ text: "Esu", value: "esu-128.png" },
	{ text: "Pride", value: "pride-128.png" },
	{ text: "Temp.no", value: "temp.no-128.png" },
	{ text: "Kingdra", value: "kingdra-128.png" },
	{ text: "Team Hurricane", value: "team-hurricane-128.png" },
	{ text: "Winstrike.ftm", value: "winstrike.ftm-128.png" },
	{ text: "Liquid", value: "liquid-128.png" },
	{ text: "Mythic", value: "mythic-128.png" },
	{ text: "Team Spirit", value: "team-spirit-128.png" },
	{ text: "Semxorah", value: "semxorah-128.png" },
	{ text: "Black Sheep", value: "black-sheep-128.png" },
	{ text: "Lgd Gaming", value: "lgd-gaming-128.png" },
	{ text: "Gx", value: "gx-128.png" },
	{ text: "Eclipse", value: "eclipse-128.png" },
	{ text: "Pries Gaming", value: "pries-gaming-128.png" },
	{ text: "Execration", value: "execration-128.png" },
	{ text: "Mousespaz", value: "mousespaz-128.png" },
	{ text: "Cerberus Esports", value: "cerberus-esports-128.png" },
	{ text: "Entity Esports", value: "entity-esports-128.png" },
	{ text: "Maple", value: "maple-128.png" },
	{ text: "Hafnet Esports", value: "hafnet-esports-128.png" },
	{ text: "Isurus Gaming", value: "isurus-gaming-128.png" },
	{ text: "Buzzkill Esports", value: "buzzkill-esports-128.png" },
	{ text: "Complexity", value: "complexity-128.png" },
	{ text: "Gamersorigin", value: "gamersorigin-128.png" },
	{ text: "Grayhound Gaming", value: "grayhound-gaming-128.png" },
	{ text: "Kt Rolster", value: "kt-rolster-128.png" },
	{ text: "Team Np", value: "team-np-128.png" },
	{ text: "Mydgb.net", value: "mydgb.net-128.png" },
	{ text: "Exdt", value: "exdt-128.png" },
	{ text: "Ignis", value: "ignis-128.png" },
	{ text: "Penguins", value: "penguins-128.png" },
	{ text: "Union Gaming Bo", value: "union-gaming-bo-128.png" },
	{ text: "Team Skyfire", value: "team-skyfire-128.png" },
	{ text: "Optic Gaming Academy", value: "optic-gaming-academy-128.png" },
	{ text: "Pabu", value: "pabu-128.png" },
	{ text: "Invictus Aquilas", value: "invictus-aquilas-128.png" },
	{ text: "Anexis Esports", value: "anexis-esports-128.png" },
	{ text: "Keen Gaming", value: "keen-gaming-128.png" },
	{ text: "We Love Gaming", value: "we-love-gaming-128.png" },
	{ text: "Werunthisplace", value: "werunthisplace-128.png" },
	{ text: "Team Team", value: "team-team-128.png" },
	{ text: "Evokate Gaming", value: "evokate-gaming-128.png" },
	{ text: "Dobryandgaming", value: "dobryandgaming-128.png" },
	{ text: "Cilekler", value: "cilekler-128.png" },
	{ text: "Hellraisers", value: "hellraisers-128.png" },
	{ text: "B.o.o.t Dreamsscape", value: "b.o.o.t-dreamsscape-128.png" },
	{ text: "Big Time Regal", value: "big-time-regal-128.png" },
	{ text: "Dragon Gate Team", value: "dragon-gate-team-128.png" },
	{ text: "Berzerk", value: "berzerk-128.png" },
	{ text: "F.r.i.e.n.d.s.", value: "f.r.i.e.n.d.s.-128.png" },
	{ text: "Sky Gaming", value: "sky-gaming-128.png" },
	{ text: "Entropy Gaming", value: "entropy-gaming-128.png" },
	{ text: "Variance Gaming", value: "variance-gaming-128.png" },
	{ text: "Voyboy", value: "voyboy-128.png" },
	{ text: "Rampage", value: "rampage-128.png" },
	{ text: "Meet Your Makers", value: "meet-your-makers-128.png" },
	{ text: "Aperture Gaming", value: "aperture-gaming-128.png" },
	{ text: "S2v Esports", value: "s2v-esports-128.png" },
	{ text: "Victory Five", value: "victory-five-128.png" },
	{ text: "Bajini Puleni", value: "bajini-puleni-128.png" },
	{ text: "Redemption Poa", value: "redemption-poa-128.png" },
	{ text: "X25 Esports", value: "x25-esports-128.png" },
	{ text: "Absolute Legends", value: "absolute-legends-128.png" },
	{ text: "Besiktas Esports Club", value: "besiktas-esports-club-128.png" },
	{ text: "Solary", value: "solary-128.png" },
	{ text: "Bilibili Gaming Junior", value: "bilibili-gaming-junior-128.png" },
	{ text: "Frag Executors", value: "frag-executors-128.png" },
	{ text: "Ig Vitality", value: "ig-vitality-128.png" },
	{ text: "Vexx Gaming", value: "vexx-gaming-128.png" },
	{ text: "Team Dilecom", value: "team-dilecom-128.png" },
	{ text: "Solaris Esports", value: "solaris-esports-128.png" },
	{ text: "Team Echo Zulu", value: "team-echo-zulu-128.png" },
	{ text: "All Gamers", value: "all-gamers-128.png" },
	{ text: "Panthers Gaming", value: "panthers-gaming-128.png" },
	{ text: "Team Fighter", value: "team-fighter-128.png" },
	{ text: "Mortal Kombat", value: "mortal-kombat-128.png" },
	{ text: "Trident Esports", value: "trident-esports-128.png" },
	{ text: "Bunny Fufuu", value: "bunny-fufuu-128.png" },
	{ text: "Evolution", value: "evolution-128.png" },
	{ text: "Squared Esports", value: "squared-esports-128.png" },
	{ text: "Flyquest", value: "flyquest-128.png" },
	{ text: "Logix E.v.", value: "logix-e.v.-128.png" },
	{ text: "Alliance", value: "alliance-128.png" },
	{ text: "Rainbow7", value: "rainbow7-128.png" },
	{ text: "N!faculty", value: "n!faculty-128.png" },
	{ text: "Qtv", value: "qtv-128.png" },
	{ text: "Crescendo", value: "crescendo-128.png" },
	{ text: "Imperial E Sports", value: "imperial-e-sports-128.png" },
	{ text: "Dynastyesc", value: "dynastyesc-128.png" },
	{ text: "Ago Esports", value: "ago-esports-128.png" },
	{ text: "Yoda", value: "yoda-128.png" },
	{ text: "Encore", value: "encore-128.png" },
	{ text: "Epsilon Esports", value: "epsilon-esports-128.png" },
	{ text: "Webspell Gaming", value: "webspell-gaming-128.png" },
	{ text: "Bluejays", value: "bluejays-128.png" },
	{ text: "Asterion Csgo", value: "asterion-csgo-128.png" },
	{ text: "Archangels", value: "archangels-128.png" },
	{ text: "Team Emprox", value: "team-emprox-128.png" },
	{ text: "Iwku Gaming", value: "iwku-gaming-128.png" },
	{ text: "Breakaway", value: "breakaway-128.png" },
	{ text: "Peekers Advantage", value: "peekers-advantage-128.png" },
	{ text: "Portal Esport", value: "portal-esport-128.png" },
	{ text: "Triumphant Song Gaming", value: "triumphant-song-gaming-128.png" },
	{ text: "Bursaspor Esports", value: "bursaspor-esports-128.png" },
	{ text: "Typhoon E Sports Club", value: "typhoon-e-sports-club-128.png" },
	{ text: "Progaming Esports", value: "progaming-esports-128.png" },
	{ text: "See You Again", value: "see-you-again-128.png" },
	{ text: "Torqued", value: "torqued-128.png" },
	{ text: "Broken Blade", value: "broken-blade-128.png" },
	{ text: "Newbee Young", value: "newbee-young-128.png" },
	{ text: "Kkona", value: "kkona-128.png" },
	{ text: "Bigtime Regal.imba", value: "bigtime-regal.imba-128.png" },
	{ text: "Team Gamerlegion", value: "team-gamerlegion-128.png" },
	{ text: "Zero Respect", value: "zero-respect-128.png" },
	{ text: "Sfto Esports", value: "sfto-esports-128.png" },
	{ text: "Sneaky", value: "sneaky-128.png" },
	{ text: "Giants", value: "giants-128.png" },
	{ text: "Game Talents", value: "game-talents-128.png" },
	{ text: "Midbeast", value: "midbeast-128.png" },
	{ text: "Valianceandco", value: "valianceandco-128.png" },
	{ text: "Team Just Alpha", value: "team-just-alpha-128.png" },
	{ text: "Legend Dragon", value: "legend-dragon-128.png" },
	{ text: "Dash9 Gaming", value: "dash9-gaming-128.png" },
	{ text: "Team Aster", value: "team-aster-128.png" },
	{ text: "Make Your Destiny", value: "make-your-destiny-128.png" },
	{ text: "Vg.flashgaming", value: "vg.flashgaming-128.png" },
	{ text: "Neon Atomic", value: "neon-atomic-128.png" },
	{ text: "Atk", value: "atk-128.png" },
	{ text: "Team Dignitas Female", value: "team-dignitas-female-128.png" },
	{ text: "Happyfeet", value: "happyfeet-128.png" },
	{ text: "Team Afro", value: "team-afro-128.png" },
	{ text: "Genuine Gaming", value: "genuine-gaming-128.png" },
	{ text: "Bbq Olivers", value: "bbq-olivers-128.png" },
	{ text: "H00liganz", value: "h00liganz-128.png" },
	{ text: "Shy", value: "shy-128.png" },
	{ text: "Boot.ds Letou", value: "boot.ds-letou-128.png" },
	{ text: "Effect", value: "effect-128.png" },
	{ text: "C4 Gaming", value: "c4-gaming-128.png" },
	{ text: "Pavaga Junior", value: "pavaga-junior-128.png" },
	{ text: "Oslo Lions", value: "oslo-lions-128.png" },
	{ text: "Szata Maga", value: "szata-maga-128.png" },
	{ text: "Envyus Academy", value: "envyus-academy-128.png" },
	{ text: "Evos Esports", value: "evos-esports-128.png" },
	{ text: "Keen Gaming Luminous", value: "keen-gaming-luminous-128.png" },
	{ text: "Gamepub", value: "gamepub-128.png" },
	{ text: "5balls", value: "5balls-128.png" },
	{ text: "Bebe", value: "bebe-128.png" },
	{ text: "Blinkpool", value: "blinkpool-128.png" },
	{ text: "Alexelcapo", value: "alexelcapo-128.png" },
	{ text: "Guerillatactic", value: "guerillatactic-128.png" },
	{ text: "100 Thieves", value: "100-thieves-128.png" },
	{ text: "Pulse Gaming", value: "pulse-gaming-128.png" },
	{ text: "Asterion", value: "asterion-128.png" },
	{ text: "Pain X", value: "pain-x-128.png" },
	{ text: "Deadpixels", value: "deadpixels-128.png" },
	{ text: "Death Trap E Sports", value: "death-trap-e-sports-128.png" },
	{ text: "Spacestation Gaming", value: "spacestation-gaming-128.png" },
	{ text: "Chaos", value: "chaos-128.png" },
	{ text: "Watch", value: "watch-128.png" },
	{ text: "Goodjob", value: "goodjob-128.png" },
	{ text: "Netcode Illuminati", value: "netcode-illuminati-128.png" },
	{ text: "Unity", value: "unity-128.png" },
	{ text: "Forge", value: "forge-128.png" },
	{ text: "Team Regicide", value: "team-regicide-128.png" },
	{ text: "Platinium Esport", value: "platinium-esport-128.png" },
	{ text: "Res Gaming", value: "res-gaming-128.png" },
	{ text: "Flytomoon", value: "flytomoon-128.png" },
	{ text: "Golden Guardians", value: "golden-guardians-128.png" },
	{ text: "Ning", value: "ning-128.png" },
	{ text: "Majesty", value: "majesty-128.png" },
	{ text: "Panthers", value: "panthers-128.png" },
	{ text: "Topsports Gaming", value: "topsports-gaming-128.png" },
	{ text: "London Conspiracy", value: "london-conspiracy-128.png" },
	{ text: "Exsequor", value: "exsequor-128.png" },
	{ text: "Offset Esports", value: "offset-esports-128.png" },
	{ text: "Vduobao", value: "vduobao-128.png" },
	{ text: "Devils.one", value: "devils.one-128.png" },
	{ text: "Jukes", value: "jukes-128.png" },
	{ text: "Psg.lgd", value: "psg.lgd-128.png" },
	{ text: "Lotac", value: "lotac-128.png" },
	{ text: "X Kom Team", value: "x-kom-team-128.png" },
	{ text: "Funplus Phoenix", value: "funplus-phoenix-128.png" },
	{ text: "Sz Absolute", value: "sz-absolute-128.png" },
	{ text: "Karont3 E Sports Club", value: "karont3-e-sports-club-128.png" },
	{ text: "Rift Esports", value: "rift-esports-128.png" },
	{ text: "Sktelecom T1", value: "sktelecom-t1-128.png" },
	{ text: "Snake Esports", value: "snake-esports-128.png" },
	{ text: "Teros E Sport", value: "teros-e-sport-128.png" },
	{ text: "Mayam Gaming", value: "mayam-gaming-128.png" },
	{ text: "24bhb", value: "24bhb-128.png" },
	{ text: "Akopalipsa", value: "akopalipsa-128.png" },
	{ text: "Team Leisure", value: "team-leisure-128.png" },
	{ text: "Elements Pro", value: "elements-pro-128.png" },
	{ text: "First Departure", value: "first-departure-128.png" },
	{ text: "Vgj.thunder", value: "vgj.thunder-128.png" },
	{ text: "Esc Gaming", value: "esc-gaming-128.png" },
	{ text: "Navi.gg.bet", value: "navi.gg.bet-128.png" },
	{ text: "Team Menace.fi", value: "team-menace.fi-128.png" },
	{ text: "Ninjas In Pyjamas", value: "ninjas-in-pyjamas-128.png" },
	{ text: "Locastic", value: "locastic-128.png" },
	{ text: "A Losers", value: "a-losers-128.png" },
	{ text: "Reflexeu", value: "reflexeu-128.png" },
	{ text: "Redemption Esports Porto Alegre", value: "redemption-esports-porto-alegre-128.png" },
	{ text: "Longzhu Gaming", value: "longzhu-gaming-128.png" },
	{ text: "Atmosphere", value: "atmosphere-128.png" },
	{ text: "Evilvice Esports", value: "evilvice-esports-128.png" },
	{ text: "X6tence", value: "x6tence-128.png" },
	{ text: "Panathinaikos Ac Esports", value: "panathinaikos-ac-esports-128.png" },
	{ text: "Rox", value: "rox-128.png" },
	{ text: "Team We", value: "team-we-128.png" },
	{ text: "Wings.red", value: "wings.red-128.png" },
	{ text: "Eyeballers", value: "eyeballers-128.png" },
	{ text: "Gripex", value: "gripex-128.png" },
	{ text: "Misfits Academy", value: "misfits-academy-128.png" },
	{ text: "Made In Thailand", value: "made-in-thailand-128.png" },
	{ text: "Wild", value: "wild-128.png" },
	{ text: "Winstrike Team", value: "winstrike-team-128.png" },
	{ text: "Vg.cyberzen", value: "vg.cyberzen-128.png" },
	{ text: "Tsm", value: "tsm-128.png" },
	{ text: "J Team", value: "j-team-128.png" },
	{ text: "Dotpixels E.v.", value: "dotpixels-e.v.-128.png" },
	{ text: "Ftv Esports", value: "ftv-esports-128.png" },
	{ text: "Noway", value: "noway-128.png" },
	{ text: "Natural 9", value: "natural-9-128.png" },
	{ text: "B.o.o.t.cn", value: "b.o.o.t.cn-128.png" },
	{ text: "Mad Team", value: "mad-team-128.png" },
	{ text: "1907 Fenerbahce Esports", value: "1907-fenerbahce-esports-128.png" },
	{ text: "Kon Norway", value: "kon-norway-128.png" },
	{ text: "Rogue Warriors ", value: "rogue-warriors--128.png" },
	{ text: "Empire Faith", value: "empire-faith-128.png" },
	{ text: "Gamezone", value: "gamezone-128.png" },
	{ text: "Vitality Bee", value: "vitality-bee-128.png" },
	{ text: "Sharks Esports", value: "sharks-esports-128.png" },
	{ text: "Team Extensive!", value: "team-extensive!-128.png" },
	{ text: "Spear Gaming", value: "spear-gaming-128.png" },
	{ text: "Astral Influence", value: "astral-influence-128.png" },
	{ text: "Eternity Gaming", value: "eternity-gaming-128.png" },
	{ text: "Rewound", value: "rewound-128.png" },
	{ text: "Edward Gaming Youth Team", value: "edward-gaming-youth-team-128.png" },
	{ text: "Team Acer", value: "team-acer-128.png" },
	{ text: "Team Shift", value: "team-shift-128.png" },
	{ text: "Singularity Female", value: "singularity-female-128.png" },
	{ text: "Team Alientech.br", value: "team-alientech.br-128.png" },
	{ text: "Ldlc.w", value: "ldlc.w-128.png" },
	{ text: "Crvena Zvezda", value: "crvena-zvezda-128.png" },
	{ text: "Team Empire", value: "team-empire-128.png" },
	{ text: "Faze Clan", value: "faze-clan-128.png" },
	{ text: "Power Gaming", value: "power-gaming-128.png" },
	{ text: "Xpc Gaming", value: "xpc-gaming-128.png" },
	{ text: "Rogue Esports Club", value: "rogue-esports-club-128.png" },
	{ text: "Gosu", value: "gosu-128.png" },
	{ text: "Art Of Cybergame", value: "art-of-cybergame-128.png" },
	{ text: "Winside", value: "winside-128.png" },
	{ text: "No Tenemos Nada", value: "no-tenemos-nada-128.png" },
	{ text: "Idm Gaming", value: "idm-gaming-128.png" },
	{ text: "Verygames", value: "verygames-128.png" },
	{ text: "Mvp Project", value: "mvp-project-128.png" },
	{ text: "Red Canids", value: "red-canids-128.png" },
	{ text: "Chiefs Esport Club", value: "chiefs-esport-club-128.png" },
	{ text: "Sg E Sports", value: "sg-e-sports-128.png" },
	{ text: "Misthy", value: "misthy-128.png" },
	{ text: "Battle Arena Elites", value: "battle-arena-elites-128.png" },
	{ text: "Cex", value: "cex-128.png" },
	{ text: "Shu Dai Xiong Gaming", value: "shu-dai-xiong-gaming-128.png" },
	{ text: "Oh My God", value: "oh-my-god-128.png" },
	{ text: "Dark Sided", value: "dark-sided-128.png" },
	{ text: "Csgoatse", value: "csgoatse-128.png" },
	{ text: "Virtus Pro", value: "virtus-pro-128.png" },
	{ text: "Sk Gaming Prime", value: "sk-gaming-prime-128.png" },
	{ text: "Edward Gaming", value: "edward-gaming-128.png" },
	{ text: "Damage Control", value: "damage-control-128.png" },
	{ text: "Team Ever", value: "team-ever-128.png" },
	{ text: "Victorious Gaming", value: "victorious-gaming-128.png" },
	{ text: "Xten Esports", value: "xten-esports-128.png" },
	{ text: "Egoboys", value: "egoboys-128.png" },
	{ text: "Delta", value: "delta-128.png" },
	{ text: "Predators Esports", value: "predators-esports-128.png" },
	{ text: "Wickd", value: "wickd-128.png" },
	{ text: "At Gaming", value: "at-gaming-128.png" },
	{ text: "Team Kinguin", value: "team-kinguin-128.png" },
	{ text: "Team Method", value: "team-method-128.png" },
	{ text: "Threats", value: "threats-128.png" },
	{ text: "X6tence Galaxy", value: "x6tence-galaxy-128.png" },
	{ text: "Begrip Gaming", value: "begrip-gaming-128.png" },
	{ text: "S1 Lykos", value: "s1-lykos-128.png" },
	{ text: "Igame Com", value: "igame-com-128.png" },
	{ text: "We Got Game", value: "we-got-game-128.png" },
	{ text: "Jiizuke", value: "jiizuke-128.png" },
	{ text: "Roar Esports", value: "roar-esports-128.png" },
	{ text: "Tigers", value: "tigers-128.png" },
	{ text: "Moss Seven Club", value: "moss-seven-club-128.png" },
	{ text: "To.be.or.not.to.be", value: "to.be.or.not.to.be-128.png" },
	{ text: "1337", value: "1337-128.png" },
	{ text: "Team Solomid", value: "team-solomid-128.png" },
	{ text: "Denial Esports", value: "denial-esports-128.png" },
	{ text: "Bau Supermassive", value: "bau-supermassive-128.png" },
	{ text: "M19 Team", value: "m19-team-128.png" },
	{ text: "Vega Squadron", value: "vega-squadron-128.png" },
	{ text: "Legend Esport Gaming", value: "legend-esport-gaming-128.png" },
	{ text: "Vp Gaming", value: "vp-gaming-128.png" },
	{ text: "Euronics Gaming", value: "euronics-gaming-128.png" },
	{ text: "Pg.orca", value: "pg.orca-128.png" },
	{ text: "7th Heaven", value: "7th-heaven-128.png" },
	{ text: "Unicorn", value: "unicorn-128.png" },
	{ text: "Legacy Esports", value: "legacy-esports-128.png" },
	{ text: "Godsent", value: "godsent-128.png" },
	{ text: "Peanut", value: "peanut-128.png" },
	{ text: "New4", value: "new4-128.png" },
	{ text: "Team Destiny", value: "team-destiny-128.png" },
	{ text: "Team Vitality", value: "team-vitality-128.png" },
	{ text: "Neon Esports", value: "neon-esports-128.png" },
	{ text: "Property", value: "property-128.png" },
	{ text: "Furia Esports", value: "furia-esports-128.png" },
	{ text: "Illuminar Gaming", value: "illuminar-gaming-128.png" },
	{ text: "Dn Gaming", value: "dn-gaming-128.png" },
	{ text: "Fab Games Esport", value: "fab-games-esport-128.png" },
	{ text: "Off The Grid", value: "off-the-grid-128.png" },
	{ text: "Cyberzen", value: "cyberzen-128.png" },
	{ text: "Complexity Gaming", value: "complexity-gaming-128.png" },
	{ text: "White Fries Gaming", value: "white-fries-gaming-128.png" },
	{ text: "Team123", value: "team123-128.png" },
	{ text: "Rookie", value: "rookie-128.png" },
	{ text: "Infernal Gamerz", value: "infernal-gamerz-128.png" },
	{ text: "Gbots Esports Club", value: "gbots-esports-club-128.png" },
	{ text: "Team Monarchs", value: "team-monarchs-128.png" },
	{ text: "Damwon Gaming", value: "damwon-gaming-128.png" },
	{ text: "Killerfish Esport", value: "killerfish-esport-128.png" },
	{ text: "Team Ibuypower", value: "team-ibuypower-128.png" },
	{ text: "Emc", value: "emc-128.png" },
	{ text: "Awsomniac", value: "awsomniac-128.png" },
	{ text: "Crvena Zvezda Esports", value: "crvena-zvezda-esports-128.png" },
	{ text: "Miami Flamingos E Sports", value: "miami-flamingos-e-sports-128.png" },
	{ text: "Progaming E Sports", value: "progaming-e-sports-128.png" },
	{ text: "Kova Esports", value: "kova-esports-128.png" },
	{ text: "Youthcrew Esports", value: "youthcrew-esports-128.png" },
	{ text: "Atb Gaming", value: "atb-gaming-128.png" },
	{ text: "Checksix Gaming", value: "checksix-gaming-128.png" },
	{ text: "Ination", value: "ination-128.png" },
	{ text: "Shiphtur", value: "shiphtur-128.png" },
	{ text: "Vultur", value: "vultur-128.png" },
	{ text: "Playing Ducks", value: "playing-ducks-128.png" },
	{ text: "Splyce Vipers", value: "splyce-vipers-128.png" },
	{ text: "Mvp Revolution", value: "mvp-revolution-128.png" },
	{ text: "Space Jam", value: "space-jam-128.png" },
	{ text: "For The Dream", value: "for-the-dream-128.png" },
	{ text: "Midas Club Elite", value: "midas-club-elite-128.png" },
	{ text: "Down To Frag", value: "down-to-frag-128.png" },
	{ text: "Team Coast", value: "team-coast-128.png" },
	{ text: "Ehome.keen", value: "ehome.keen-128.png" },
	{ text: "Godlike", value: "godlike-128.png" },
	{ text: "Playmakers Esports", value: "playmakers-esports-128.png" },
	{ text: "Cheeseltd", value: "cheeseltd-128.png" },
	{ text: "Sterling Global Dragons", value: "sterling-global-dragons-128.png" },
	{ text: "Gambit Esports", value: "gambit-esports-128.png" },
	{ text: "Careta", value: "careta-128.png" },
	{ text: "Og", value: "og-128.png" },
	{ text: "Warthox Esport", value: "warthox-esport-128.png" },
	{ text: "Summa.gg", value: "summa.gg-128.png" },
	{ text: "Candice", value: "candice-128.png" },
	{ text: "Team Red", value: "team-red-128.png" },
	{ text: "Team Leviathan", value: "team-leviathan-128.png" },
	{ text: "G Pride", value: "g-pride-128.png" },
	{ text: "Funplus Phoenix Blaze", value: "funplus-phoenix-blaze-128.png" },
	{ text: "Raiders", value: "raiders-128.png" },
	{ text: "Pentagram G Shock", value: "pentagram-g-shock-128.png" },
	{ text: "Team Horizon Reapers", value: "team-horizon-reapers-128.png" },
	{ text: "Ezskins.com", value: "ezskins.com-128.png" },
	{ text: "Ldlc.b", value: "ldlc.b-128.png" },
	{ text: "Team Dynamic", value: "team-dynamic-128.png" },
	{ text: "As Trencin Esports", value: "as-trencin-esports-128.png" },
	{ text: "Clutch Gamers", value: "clutch-gamers-128.png" },
	{ text: "Riot Squad", value: "riot-squad-128.png" },
	{ text: "Taskus Titans", value: "taskus-titans-128.png" },
	{ text: "Team Singularity", value: "team-singularity-128.png" },
	{ text: "Warlegend", value: "warlegend-128.png" },
	{ text: "Rox Tigers", value: "rox-tigers-128.png" },
	{ text: "Team Reapers", value: "team-reapers-128.png" },
	{ text: "Tempo Storm", value: "tempo-storm-128.png" },
	{ text: "Team Battlecomics", value: "team-battlecomics-128.png" },
	{ text: "Ghost Gaming", value: "ghost-gaming-128.png" },
	{ text: "Suning Gaming S", value: "suning-gaming-s-128.png" },
	{ text: "Espada", value: "espada-128.png" },
	{ text: "Progaming.td", value: "progaming.td-128.png" },
	{ text: "Surge Esports Club", value: "surge-esports-club-128.png" },
	{ text: "Xapso", value: "xapso-128.png" },
	{ text: "Vws Gaming", value: "vws-gaming-128.png" },
	{ text: "Inshock", value: "inshock-128.png" },
	{ text: "Madlife", value: "madlife-128.png" },
	{ text: "Faker", value: "faker-128.png" },
	{ text: "Space Station", value: "space-station-128.png" },
	{ text: "Athletico Bh", value: "athletico-bh-128.png" },
	{ text: "Moviestar Riders", value: "moviestar-riders-128.png" },
	{ text: "Ggwp.pro", value: "ggwp.pro-128.png" },
	{ text: "Evidence E Sports", value: "evidence-e-sports-128.png" },
	{ text: "Pc419", value: "pc419-128.png" },
	{ text: "Baroibeo", value: "baroibeo-128.png" },
	{ text: "3sup Enterprises", value: "3sup-enterprises-128.png" },
	{ text: "Escape Gaming", value: "escape-gaming-128.png" },
	{ text: "Granit Gaming", value: "granit-gaming-128.png" },
	{ text: "Pg Barracx", value: "pg-barracx-128.png" },
	{ text: "Ad Finem", value: "ad-finem-128.png" },
	{ text: "Fam143", value: "fam143-128.png" },
	{ text: "Midas Club", value: "midas-club-128.png" },
	{ text: "Zagreb 360 Gaming", value: "zagreb-360-gaming-128.png" },
	{ text: "Enso", value: "enso-128.png" },
	{ text: "Royals", value: "royals-128.png" },
	{ text: "Crest Gaming", value: "crest-gaming-128.png" },
	{ text: "Invictus Gaming", value: "invictus-gaming-128.png" },
	{ text: "Breakaway Esports", value: "breakaway-esports-128.png" },
	{ text: "Hippomaniacs", value: "hippomaniacs-128.png" },
	{ text: "Roccat", value: "roccat-128.png" },
	{ text: "Counter Logic Gaming", value: "counter-logic-gaming-128.png" },
	{ text: "Gravitas", value: "gravitas-128.png" },
	{ text: "Vision Gaming", value: "vision-gaming-128.png" },
	{ text: "Monomaniac Esports", value: "monomaniac-esports-128.png" },
	{ text: "Royal Club", value: "royal-club-128.png" },
	{ text: "Fnatic Rising", value: "fnatic-rising-128.png" },
	{ text: "Lng Esports", value: "lng-esports-128.png" },
	{ text: "Taboo", value: "taboo-128.png" },
	{ text: "Cavalry", value: "cavalry-128.png" },
	{ text: "Operation Kino", value: "operation-kino-128.png" },
	{ text: "Polar Ace Esports", value: "polar-ace-esports-128.png" },
	{ text: "Superjymy", value: "superjymy-128.png" },
	{ text: "Goliath Gaming", value: "goliath-gaming-128.png" },
	{ text: "Flash Wolves", value: "flash-wolves-128.png" },
	{ text: "Hollywood", value: "hollywood-128.png" },
	{ text: "The Final Tribe", value: "the-final-tribe-128.png" },
	{ text: "Hanwha Life Esports", value: "hanwha-life-esports-128.png" },
	{ text: "Neophyte", value: "neophyte-128.png" },
	{ text: "Plugo", value: "plugo-128.png" },
	{ text: "Majestic Esports", value: "majestic-esports-128.png" },
	{ text: "Vault.gg", value: "vault.gg-128.png" },
	{ text: "Splyce", value: "splyce-128.png" },
	{ text: "9z Team", value: "9z-team-128.png" },
	{ text: "Team Faceless", value: "team-faceless-128.png" },
	{ text: "K1ck Esports Club", value: "k1ck-esports-club-128.png" },
	{ text: "Begenius Esc", value: "begenius-esc-128.png" },
	{ text: "Team Winfakt", value: "team-winfakt-128.png" },
	{ text: "Just Toys Havoks", value: "just-toys-havoks-128.png" },
	{ text: "Clutchit.org", value: "clutchit.org-128.png" },
	{ text: "Orange Esports", value: "orange-esports-128.png" },
	{ text: "Mineski", value: "mineski-128.png" },
	{ text: "Ground Zero", value: "ground-zero-128.png" },
	{ text: "Future.club", value: "future.club-128.png" },
	{ text: "Frenchfrogs", value: "frenchfrogs-128.png" },
	{ text: "Team 3d", value: "team-3d-128.png" },
	{ text: "Playart", value: "playart-128.png" },
	{ text: "Enro Griffins", value: "enro-griffins-128.png" },
	{ text: "Big Gods", value: "big-gods-128.png" },
	{ text: "Istanbul Wild Cats", value: "istanbul-wild-cats-128.png" },
	{ text: "Cplay", value: "cplay-128.png" },
	{ text: "Natus Vincere.cis", value: "natus-vincere.cis-128.png" },
	{ text: "Alpha Gaming", value: "alpha-gaming-128.png" },
	{ text: "Mad Like Wizards", value: "mad-like-wizards-128.png" },
	{ text: "Mad Lions", value: "mad-lions-128.png" },
	{ text: "Kliktech", value: "kliktech-128.png" },
	{ text: "Emonkeyz", value: "emonkeyz-128.png" },
	{ text: "Maknitude", value: "maknitude-128.png" },
	{ text: "Random 5", value: "random-5-128.png" },
	{ text: "Lpsp", value: "lpsp-128.png" },
	{ text: "Warmaker", value: "warmaker-128.png" },
	{ text: "Eunited", value: "eunited-128.png" },
	{ text: "Team Yetti", value: "team-yetti-128.png" },
	{ text: "Giants Gaming Spain", value: "giants-gaming-spain-128.png" },
	{ text: "Publiclir.se", value: "publiclir.se-128.png" },
	{ text: "Dark Horse", value: "dark-horse-128.png" },
	{ text: "Spirit Of Amiga", value: "spirit-of-amiga-128.png" },
	{ text: "Binary Dragons", value: "binary-dragons-128.png" },
	{ text: "Unicorns Of Love", value: "unicorns-of-love-128.png" },
	{ text: "Ronin", value: "ronin-128.png" },
	{ text: "Nyyrikki Esports", value: "nyyrikki-esports-128.png" },
	{ text: "Team Xolotl", value: "team-xolotl-128.png" },
	{ text: "Axiz", value: "axiz-128.png" },
	{ text: "Team Admiral", value: "team-admiral-128.png" },
	{ text: "Flipsid3 Tactics", value: "flipsid3-tactics-128.png" },
	{ text: "Brussels Guardians", value: "brussels-guardians-128.png" },
	{ text: "Recursive Esports", value: "recursive-esports-128.png" },
	{ text: "Aster.aquarius", value: "aster.aquarius-128.png" },
	{ text: "Mk3 E Sports", value: "mk3-e-sports-128.png" },
	{ text: "Singularity Esports", value: "singularity-esports-128.png" },
	{ text: "Force Of Nature", value: "force-of-nature-128.png" },
	{ text: "Pries", value: "pries-128.png" },
	{ text: "Tierwulf", value: "tierwulf-128.png" },
	{ text: "Line5", value: "line5-128.png" },
	{ text: "Beastcoast", value: "beastcoast-128.png" },
	{ text: "Samsung Galaxy", value: "samsung-galaxy-128.png" },
	{ text: "Azio Esports", value: "azio-esports-128.png" },
	{ text: "Wicked Esports", value: "wicked-esports-128.png" },
	{ text: "Paradox Gaming", value: "paradox-gaming-128.png" },
	{ text: "Pats Money Crew", value: "pats-money-crew-128.png" },
	{ text: "Detona", value: "detona-128.png" },
	{ text: "Clutch Gaming", value: "clutch-gaming-128.png" },
	{ text: "Team Property", value: "team-property-128.png" },
	{ text: "Gen.g Esports", value: "gen.g-esports-128.png" },
	{ text: "Prospects", value: "prospects-128.png" },
	{ text: "Slashlevel", value: "slashlevel-128.png" },
	{ text: "Vikings", value: "vikings-128.png" },
	{ text: "Cdec Gaming", value: "cdec-gaming-128.png" },
	{ text: "Dark Tigers", value: "dark-tigers-128.png" },
	{ text: "Skitlite Gaming", value: "skitlite-gaming-128.png" },
	{ text: "B.o.o.t Dreamscape", value: "b.o.o.t-dreamscape-128.png" },
	{ text: "Budapest5", value: "budapest5-128.png" },
	{ text: "Lounge Gaming", value: "lounge-gaming-128.png" },
	{ text: "Trz", value: "trz-128.png" },
	{ text: "Team Infused", value: "team-infused-128.png" },
	{ text: "Fc Schalke 04", value: "fc-schalke-04-128.png" },
	{ text: "Sinners", value: "sinners-128.png" },
	{ text: "Alternate Attax", value: "alternate-attax-128.png" },
	{ text: "Madjick Gaming", value: "madjick-gaming-128.png" },
	{ text: "Bpro Gaming", value: "bpro-gaming-128.png" },
	{ text: "Team Heretics", value: "team-heretics-128.png" },
	{ text: "Team Cursive", value: "team-cursive-128.png" },
	{ text: "Lingan E Sport", value: "lingan-e-sport-128.png" },
	{ text: "Raise Gaming", value: "raise-gaming-128.png" },
	{ text: "Line5 Academy", value: "line5-academy-128.png" },
	{ text: "Cloud9 Academy", value: "cloud9-academy-128.png" },
	{ text: "D7g Esports Club", value: "d7g-esports-club-128.png" },
	{ text: "Enervate Gaming", value: "enervate-gaming-128.png" },
	{ text: "Order", value: "order-128.png" },
	{ text: "Team Rock", value: "team-rock-128.png" },
	{ text: "Storm Rider", value: "storm-rider-128.png" },
	{ text: "Evi", value: "evi-128.png" },
	{ text: "Team Phenomenon", value: "team-phenomenon-128.png" },
	{ text: "Galatasaray Esports", value: "galatasaray-esports-128.png" },
	{ text: "Royal Bandits", value: "royal-bandits-128.png" },
	{ text: "Team X", value: "team-x-128.png" },
	{ text: "Ares Female", value: "ares-female-128.png" },
	{ text: "Team Eu4ia", value: "team-eu4ia-128.png" },
	{ text: "Gaming Gaming", value: "gaming-gaming-128.png" },
	{ text: "Outplayed", value: "outplayed-128.png" },
	{ text: "Western Wolves", value: "western-wolves-128.png" },
	{ text: "Exdee Gaming", value: "exdee-gaming-128.png" },
	{ text: "Team Gamerdesk", value: "team-gamerdesk-128.png" },
	{ text: "Pavaga Gaming", value: "pavaga-gaming-128.png" },
	{ text: "Selfless Gaming", value: "selfless-gaming-128.png" },
	{ text: "Gambit", value: "gambit-128.png" },
	{ text: "Digital Chaos", value: "digital-chaos-128.png" },
	{ text: "Team Adroit", value: "team-adroit-128.png" },
	{ text: "Final Feature", value: "final-feature-128.png" },
	{ text: "Team Maple", value: "team-maple-128.png" },
	{ text: "Team Webone", value: "team-webone-128.png" },
	{ text: "Old Guys Club", value: "old-guys-club-128.png" },
	{ text: "Team Freedom", value: "team-freedom-128.png" },
	{ text: "3dmax", value: "3dmax-128.png" },
	{ text: "Extatus", value: "extatus-128.png" },
	{ text: "Wings Gaming", value: "wings-gaming-128.png" },
	{ text: "Artifact", value: "artifact-128.png" },
	{ text: "Ground Zero Gaming", value: "ground-zero-gaming-128.png" },
	{ text: "Intech Tenerife Titans", value: "intech-tenerife-titans-128.png" },
	{ text: "Flyquest Academy", value: "flyquest-academy-128.png" },
	{ text: "Origen", value: "origen-128.png" },
	{ text: "Ding Sheng Gaming", value: "ding-sheng-gaming-128.png" },
	{ text: "Gplay.bg", value: "gplay.bg-128.png" },
	{ text: "Unique Team", value: "unique-team-128.png" },
	{ text: "Revenge Gaming", value: "revenge-gaming-128.png" },
	{ text: "Avez", value: "avez-128.png" },
	{ text: "Carnage Esports", value: "carnage-esports-128.png" },
	{ text: "Excel Esports", value: "excel-esports-128.png" },
	{ text: "Mastermind", value: "mastermind-128.png" },
	{ text: "London Lynx", value: "london-lynx-128.png" },
	{ text: "Signify", value: "signify-128.png" },
	{ text: "Team Ldlc", value: "team-ldlc-128.png" },
	{ text: "Kon Finland", value: "kon-finland-128.png" },
	{ text: "Cex Eps", value: "cex-eps-128.png" },
	{ text: "Forze", value: "forze-128.png" },
	{ text: "Mibr", value: "mibr-128.png" },
	{ text: "Fmesports", value: "fmesports-128.png" },
	{ text: "Neronity", value: "neronity-128.png" },
	{ text: "Tyloo", value: "tyloo-128.png" },
	{ text: "Flow", value: "flow-128.png" },
	{ text: "Intz Esports", value: "intz-esports-128.png" },
	{ text: "Emulate!", value: "emulate!-128.png" },
	{ text: "Wololos", value: "wololos-128.png" },
	{ text: "Maxandrelax", value: "maxandrelax-128.png" },
	{ text: "Kpv", value: "kpv-128.png" },
	{ text: "Mineski X", value: "mineski-x-128.png" },
	{ text: "Etab", value: "etab-128.png" },
	{ text: "Cringe Gods", value: "cringe-gods-128.png" },
	{ text: "Conquer Gaming", value: "conquer-gaming-128.png" },
	{ text: "Gameplaydna", value: "gameplaydna-128.png" },
	{ text: "Boom Id", value: "boom-id-128.png" },
	{ text: "Marines Esports", value: "marines-esports-128.png" },
	{ text: "Dreamscape", value: "dreamscape-128.png" },
	{ text: "Klicktech", value: "klicktech-128.png" },
	{ text: "Infinity", value: "infinity-128.png" },
	{ text: "Dragons Ec", value: "dragons-ec-128.png" },
	{ text: "Furia Academy", value: "furia-academy-128.png" },
	{ text: "Echo Fox Academy", value: "echo-fox-academy-128.png" },
	{ text: "G3nerationx", value: "g3nerationx-128.png" },
	{ text: "Exalty", value: "exalty-128.png" },
	{ text: "Ahq E Sports Club", value: "ahq-e-sports-club-128.png" },
	{ text: "Windigo Gaming", value: "windigo-gaming-128.png" },
	{ text: "Fish123", value: "fish123-128.png" },
	{ text: "Rakin", value: "rakin-128.png" },
	{ text: "Titans Esports", value: "titans-esports-128.png" },
	{ text: "Nobo", value: "nobo-128.png" },
	{ text: "Radix Esports", value: "radix-esports-128.png" },
	{ text: "Cherry Gaming", value: "cherry-gaming-128.png" },
	{ text: "Team Quest", value: "team-quest-128.png" },
	{ text: "5power Gaming", value: "5power-gaming-128.png" },
	{ text: "Nrg Esports", value: "nrg-esports-128.png" },
	{ text: "Bombers", value: "bombers-128.png" },
	{ text: "Winterfox", value: "winterfox-128.png" },
	{ text: "Team Max", value: "team-max-128.png" },
	{ text: "Nextplease!", value: "nextplease!-128.png" },
	{ text: "Team Wild Fire", value: "team-wild-fire-128.png" },
	{ text: "Tnc Pro Team", value: "tnc-pro-team-128.png" },
	{ text: "Alpha Red", value: "alpha-red-128.png" },
	{ text: "Inflames", value: "inflames-128.png" },
	{ text: "Gambit Youngsters", value: "gambit-youngsters-128.png" },
	{ text: "Gtz Bulls Esports", value: "gtz-bulls-esports-128.png" },
	{ text: "Nihilum Gaming", value: "nihilum-gaming-128.png" },
	{ text: "Santos Dexterity", value: "santos-dexterity-128.png" },
	{ text: "Chiefs Esports Club", value: "chiefs-esports-club-128.png" },
	{ text: "Melty Esport Club", value: "melty-esport-club-128.png" },
	{ text: "Infinity Esports", value: "infinity-esports-128.png" },
	{ text: "Nexus Gaming", value: "nexus-gaming-128.png" },
	{ text: "Young Miracles", value: "young-miracles-128.png" },
	{ text: "Ehome.luminous", value: "ehome.luminous-128.png" },
	{ text: "Fluffy Gangsters", value: "fluffy-gangsters-128.png" },
	{ text: "Ago Gaming", value: "ago-gaming-128.png" },
	{ text: "Exertus Esports", value: "exertus-esports-128.png" },
	{ text: "Plink Tech", value: "plink-tech-128.png" },
	{ text: "Counter Logic Gaming Academy", value: "counter-logic-gaming-academy-128.png" },
	{ text: "Wisla Plock Esports", value: "wisla-plock-esports-128.png" },
	{ text: "Heroic", value: "heroic-128.png" },
	{ text: "Royal Never Give Up", value: "royal-never-give-up-128.png" },
	{ text: "Resurgence", value: "resurgence-128.png" },
	{ text: "Young Glory", value: "young-glory-128.png" },
	{ text: "Cyber Anji", value: "cyber-anji-128.png" },
	{ text: "Intz E Sports", value: "intz-e-sports-128.png" },
	{ text: "Gz", value: "gz-128.png" },
	{ text: "Mega", value: "mega-128.png" },
	{ text: "Ferzee", value: "ferzee-128.png" },
	{ text: "Sinister", value: "sinister-128.png" },
	{ text: "Noble Esports", value: "noble-esports-128.png" },
	{ text: "Big 5 Esports", value: "big-5-esports-128.png" },
	{ text: "Syfgaming", value: "syfgaming-128.png" },
	{ text: "Mc E Sports", value: "mc-e-sports-128.png" },
	{ text: "Team Envyus", value: "team-envyus-128.png" },
	{ text: "Trifecta Gaming", value: "trifecta-gaming-128.png" },
	{ text: "Ux Gaming", value: "ux-gaming-128.png" },
	{ text: "Vaevictis Esports", value: "vaevictis-esports-128.png" },
	{ text: "Caseking Gaming", value: "caseking-gaming-128.png" },
	{ text: "Sk Gaming", value: "sk-gaming-128.png" },
	{ text: "Dire Wolves", value: "dire-wolves-128.png" },
	{ text: "Area 51 Gaming", value: "area-51-gaming-128.png" },
	{ text: "Avangar", value: "avangar-128.png" },
	{ text: "Rogue", value: "rogue-128.png" },
	{ text: "Team Vgj", value: "team-vgj-128.png" },
	{ text: "Double Dimension", value: "double-dimension-128.png" },
	{ text: "Maxisaucisse", value: "maxisaucisse-128.png" },
	{ text: "Ventus Esports", value: "ventus-esports-128.png" },
	{ text: "Method", value: "method-128.png" },
	{ text: "Wind And Rain", value: "wind-and-rain-128.png" },
	{ text: "P3p Esports", value: "p3p-esports-128.png" },
	{ text: "Clutch Gaming Academy", value: "clutch-gaming-academy-128.png" },
	{ text: "Team Orbit", value: "team-orbit-128.png" },
	{ text: "Dark Passage", value: "dark-passage-128.png" },
	{ text: "Immortals", value: "immortals-128.png" },
	{ text: "Phoenix1", value: "phoenix1-128.png" },
	{ text: "Hong Kong Esports", value: "hong-kong-esports-128.png" },
	{ text: "Lucid Dream", value: "lucid-dream-128.png" },
	{ text: "Swole Patrol", value: "swole-patrol-128.png" },
	{ text: "Evil Geniuses", value: "evil-geniuses-128.png" },
	{ text: "Magistra", value: "magistra-128.png" },
	{ text: "Team Liquid", value: "team-liquid-128.png" },
	{ text: "Pride Gaming", value: "pride-gaming-128.png" },
	{ text: "Cignal Ultra", value: "cignal-ultra-128.png" },
	{ text: "Rise Nation", value: "rise-nation-128.png" },
	{ text: "Dendd", value: "dendd-128.png" },
	{ text: "Team Refuse", value: "team-refuse-128.png" },
	{ text: "Team Dynamics", value: "team-dynamics-128.png" },
	{ text: "Mammoth", value: "mammoth-128.png" },
	{ text: "Mvp Pk", value: "mvp-pk-128.png" },
	{ text: "Rctic Esports", value: "rctic-esports-128.png" },
	{ text: "Syman Gaming", value: "syman-gaming-128.png" },
	{ text: "Firegamers", value: "firegamers-128.png" },
	{ text: "Team Serenity", value: "team-serenity-128.png" },
	{ text: "Mvp", value: "mvp-128.png" },
	{ text: "Tnc Tigers", value: "tnc-tigers-128.png" },
	{ text: "Astana Dragons", value: "astana-dragons-128.png" },
	{ text: "Sin Gaming", value: "sin-gaming-128.png" },
	{ text: "Speedlink", value: "speedlink-128.png" },
	{ text: "Misfits Gaming", value: "misfits-gaming-128.png" },
	{ text: "Tempo Gaming", value: "tempo-gaming-128.png" },
	{ text: "Rng", value: "rng-128.png" },
	{ text: "FREE AGENT", value: "free agent" }, //TODO: Placeholder
	{ text: "BENCH", value: "bench" } //TODO: Placeholder
]
